on:
  push: 
    branches:
      - master










jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing Gitgub action'
        run: pwd

      - name: 'Testing printing'
        run: echo Yara
        
